import type { DistrictData } from './types';

export const TELANGANA_CENTER: [number, number] = [17.8749, 79.1557];

export const TELANGANA_BOUNDS: [[number, number], [number, number]] = [
  [15.6, 76.8], // Southwest
  [20.0, 81.8], // Northeast
];

export const TELANGANA_DISTRICTS: DistrictData[] = [
  {
    id: 'adilabad',
    name: 'Adilabad',
    code: '532',
    lat: 19.5032,
    lng: 78.55,
    zone: 'Northern Telangana',
    headquarters: 'Adilabad',
    jobCount: 48,
    companiesCount: 16,
  },
  {
    id: 'bhadradri-kothagudem',
    name: 'Bhadradri Kothagudem',
    code: '753',
    lat: 17.6864,
    lng: 80.7178,
    zone: 'Eastern Telangana',
    headquarters: 'Kothagudem',
    jobCount: 72,
    companiesCount: 24,
  },
  {
    id: 'hyderabad',
    name: 'Hyderabad',
    code: '536',
    lat: 17.4001,
    lng: 78.4713,
    zone: 'Capital / Central',
    headquarters: 'Hyderabad',
    jobCount: 1840,
    companiesCount: 420,
  },
  {
    id: 'jagtial',
    name: 'Jagtial',
    code: '737',
    lat: 18.7896,
    lng: 78.8983,
    zone: 'Northern Telangana',
    headquarters: 'Jagtial',
    jobCount: 52,
    companiesCount: 18,
  },
  {
    id: 'jangaon',
    name: 'Jangaon',
    code: '752',
    lat: 17.7273,
    lng: 79.2819,
    zone: 'Central Telangana',
    headquarters: 'Jangaon',
    jobCount: 36,
    companiesCount: 12,
  },
  {
    id: 'jayashankar-bhupalapally',
    name: 'Jayashankar Bhupalapally',
    code: '750',
    lat: 18.4836,
    lng: 79.8368,
    zone: 'Eastern Telangana',
    headquarters: 'Bhupalpally',
    jobCount: 34,
    companiesCount: 10,
  },
  {
    id: 'jogulamba-gadwal',
    name: 'Jogulamba Gadwal',
    code: '744',
    lat: 16.0661,
    lng: 77.8152,
    zone: 'Southern Telangana',
    headquarters: 'Gadwal',
    jobCount: 38,
    companiesCount: 14,
  },
  {
    id: 'kamareddy',
    name: 'Kamareddy',
    code: '736',
    lat: 18.294,
    lng: 78.0554,
    zone: 'Northern Telangana',
    headquarters: 'Kamareddy',
    jobCount: 45,
    companiesCount: 15,
  },
  {
    id: 'karimnagar',
    name: 'Karimnagar',
    code: '534',
    lat: 18.3946,
    lng: 79.2021,
    zone: 'Northern Telangana',
    headquarters: 'Karimnagar',
    jobCount: 215,
    companiesCount: 68,
  },
  {
    id: 'khammam',
    name: 'Khammam',
    code: '541',
    lat: 17.1964,
    lng: 80.366,
    zone: 'Eastern Telangana',
    headquarters: 'Khammam',
    jobCount: 195,
    companiesCount: 55,
  },
  {
    id: 'komaram-bheem',
    name: 'Komaram Bheem',
    code: '733',
    lat: 19.3493,
    lng: 79.3741,
    zone: 'Northern Telangana',
    headquarters: 'Asifabad',
    jobCount: 28,
    companiesCount: 9,
  },
  {
    id: 'mahabubabad',
    name: 'Mahabubabad',
    code: '751',
    lat: 17.6398,
    lng: 79.9104,
    zone: 'Eastern Telangana',
    headquarters: 'Mahabubabad',
    jobCount: 33,
    companiesCount: 11,
  },
  {
    id: 'mahabubnagar',
    name: 'Mahabubnagar',
    code: '538',
    lat: 16.7713,
    lng: 77.9852,
    zone: 'Southern Telangana',
    headquarters: 'Mahabubnagar',
    jobCount: 110,
    companiesCount: 35,
  },
  {
    id: 'mancherial',
    name: 'Mancherial',
    code: '735',
    lat: 19.0366,
    lng: 79.4576,
    zone: 'Northern Telangana',
    headquarters: 'Mancherial',
    jobCount: 68,
    companiesCount: 22,
  },
  {
    id: 'medak',
    name: 'Medak',
    code: '535',
    lat: 17.9603,
    lng: 78.2382,
    zone: 'Western Telangana',
    headquarters: 'Medak',
    jobCount: 62,
    companiesCount: 20,
  },
  {
    id: 'medchal-malkajgiri',
    name: 'Medchal Malkajgiri',
    code: '742',
    lat: 17.5176,
    lng: 78.5471,
    zone: 'Hyderabad Metropolitan',
    headquarters: 'Medchal',
    jobCount: 650,
    companiesCount: 185,
  },
  {
    id: 'mulugu',
    name: 'Mulugu',
    code: '780',
    lat: 18.2157,
    lng: 80.3076,
    zone: 'Eastern Telangana',
    headquarters: 'Mulugu',
    jobCount: 22,
    companiesCount: 8,
  },
  {
    id: 'nagarkurnool',
    name: 'Nagarkurnool',
    code: '746',
    lat: 16.439,
    lng: 78.5592,
    zone: 'Southern Telangana',
    headquarters: 'Nagarkurnool',
    jobCount: 39,
    companiesCount: 13,
  },
  {
    id: 'nalgonda',
    name: 'Nalgonda',
    code: '539',
    lat: 16.8881,
    lng: 79.0507,
    zone: 'Southern Telangana',
    headquarters: 'Nalgonda',
    jobCount: 140,
    companiesCount: 42,
  },
  {
    id: 'narayanpet',
    name: 'Narayanpet',
    code: '781',
    lat: 16.6979,
    lng: 77.5813,
    zone: 'Southern Telangana',
    headquarters: 'Narayanpet',
    jobCount: 26,
    companiesCount: 9,
  },
  {
    id: 'nirmal',
    name: 'Nirmal',
    code: '734',
    lat: 19.1149,
    lng: 78.3294,
    zone: 'Northern Telangana',
    headquarters: 'Nirmal',
    jobCount: 42,
    companiesCount: 14,
  },
  {
    id: 'nizamabad',
    name: 'Nizamabad',
    code: '533',
    lat: 18.6896,
    lng: 78.2678,
    zone: 'Northern Telangana',
    headquarters: 'Nizamabad',
    jobCount: 185,
    companiesCount: 58,
  },
  {
    id: 'peddapalli',
    name: 'Peddapalli',
    code: '738',
    lat: 18.6251,
    lng: 79.422,
    zone: 'Northern Telangana',
    headquarters: 'Peddapalli',
    jobCount: 75,
    companiesCount: 26,
  },
  {
    id: 'rajanna-sircilla',
    name: 'Rajanna Sircilla',
    code: '739',
    lat: 18.4118,
    lng: 78.7548,
    zone: 'Northern Telangana',
    headquarters: 'Sircilla',
    jobCount: 56,
    companiesCount: 19,
  },
  {
    id: 'ranga-reddy',
    name: 'Ranga Reddy',
    code: '537',
    lat: 17.1525,
    lng: 78.4194,
    zone: 'Hyderabad Metropolitan',
    headquarters: 'Shamshabad',
    jobCount: 720,
    companiesCount: 210,
  },
  {
    id: 'sangareddy',
    name: 'Sangareddy',
    code: '740',
    lat: 17.8013,
    lng: 77.9395,
    zone: 'Western Telangana',
    headquarters: 'Sangareddy',
    jobCount: 190,
    companiesCount: 65,
  },
  {
    id: 'siddipet',
    name: 'Siddipet',
    code: '741',
    lat: 18.0356,
    lng: 78.8662,
    zone: 'Central Telangana',
    headquarters: 'Siddipet',
    jobCount: 88,
    companiesCount: 29,
  },
  {
    id: 'suryapet',
    name: 'Suryapet',
    code: '748',
    lat: 17.196,
    lng: 79.7103,
    zone: 'Southern Telangana',
    headquarters: 'Suryapet',
    jobCount: 64,
    companiesCount: 21,
  },
  {
    id: 'vikarabad',
    name: 'Vikarabad',
    code: '743',
    lat: 17.2387,
    lng: 77.7607,
    zone: 'Western Telangana',
    headquarters: 'Vikarabad',
    jobCount: 46,
    companiesCount: 15,
  },
  {
    id: 'wanaparthy',
    name: 'Wanaparthy',
    code: '745',
    lat: 16.3011,
    lng: 78.048,
    zone: 'Southern Telangana',
    headquarters: 'Wanaparthy',
    jobCount: 35,
    companiesCount: 12,
  },
  {
    id: 'warangal-rural',
    name: 'Warangal Rural',
    code: '749',
    lat: 17.9218,
    lng: 79.7022,
    zone: 'Central Telangana',
    headquarters: 'Geesugonda',
    jobCount: 78,
    companiesCount: 25,
  },
  {
    id: 'warangal-urban',
    name: 'Warangal Urban',
    code: '540',
    lat: 18.0207,
    lng: 79.5036,
    zone: 'Central Telangana',
    headquarters: 'Hanamkonda',
    jobCount: 310,
    companiesCount: 92,
  },
  {
    id: 'yadadri-bhuvanagiri',
    name: 'Yadadri Bhuvanagiri',
    code: '747',
    lat: 17.4256,
    lng: 78.9897,
    zone: 'Central Telangana',
    headquarters: 'Bhuvanagiri',
    jobCount: 82,
    companiesCount: 27,
  },
];
